# Generated by Django 5.1.7 on 2025-05-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('organization', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('partner_type', models.CharField(choices=[('distributor', 'Distributor'), ('ngo', 'NGO'), ('government', 'Government'), ('research', 'Research Institution'), ('other', 'Other')], max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['name'],
            },
        ),
    ]
