# Generated by Django 5.1.7 on 2025-05-09 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('amount_needed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_return', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('risk_level', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Investment Opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investors.investmentopportunity')),
            ],
            options={
                'verbose_name_plural': 'Investor Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
